services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:80"
    volumes:
      - /volume1/docker/ECHO/data/ensub/database/database.sqlite:/var/www/html/database/database.sqlite
    restart: unless-stopped
